---
- name: Ensures /home/ubuntu/project dir exists
  file: path=/home/ubuntu/project state=directory

- name: Use template to create k8s.yaml
  template:
    src: ./templates/k8s.j2
    dest: /home/ubuntu/project/k8s.yaml
