---
- name: register ca variable
  vars:
    name: 'github-token'
  environment:
    KUBECONFIG: /.kube/config
  shell: kubectl get -n {{sample_app_name}} secret/$(kubectl -n {{sample_app_name}} get secret | awk '/^{{name}}-/{print $1}') -o jsonpath='{.data.ca\.crt}'
  register: ca

- name: register token variable
  vars:
    name: 'github-token'
  environment:
    KUBECONFIG: /.kube/config
  shell: kubectl get -n {{sample_app_name}} secret/$(kubectl -n {{sample_app_name}}  get secret | awk '/^{{name}}-/{print $1}') -o jsonpath='{.data.token}' | base64 --decode
  register: token

- name: Use template to create kubeconfig.yaml
  vars:
    server: "https://{{hostvars[groups['k8s_cluster'][0]].ansible_host}}:6443"
  template:
    src: ./templates/kubeconfig.j2
    dest: /home/ubuntu/project/kubeconfig.yaml
