---
- name: register SA_SECRET_TOKEN
  vars:
    name: 'github'
  environment:
    KUBECONFIG: /.kube/config
  shell: kubectl -n {{sample_app_name}} get secret/{{name}} {% raw %} -o=go-template='{{.data.token}}' {% endraw %} | base64 --decode
  register: SA_SECRET_TOKEN

- name: register CLUSTER_NAME
  environment:
    KUBECONFIG: /.kube/config
  shell: kubectl config current-context
  register: CLUSTER_NAME

- name: register CURRENT_CLUSTER
  environment:
    KUBECONFIG: /.kube/config
  shell: kubectl {% raw %}config view --raw -o=go-template='{{range .contexts}}{{if eq .name "'''{% endraw %}{{CLUSTER_NAME.stdout}}{% raw %}'''"}}{{ index .context "cluster" }}{{end}}{{end}}'{% endraw %}
  register: CURRENT_CLUSTER

- name: register CLUSTER_CA_CERT
  environment:
    KUBECONFIG: /.kube/config
  shell: kubectl {% raw %}config view --raw -o=go-template='{{range .clusters}}{{if eq .name "'''{% endraw %}{{CURRENT_CLUSTER.stdout}}{% raw %}'''"}}"{{with index .cluster "certificate-authority-data" }}{{.}}{{end}}"{{ end }}{{ end }}'{% endraw %}
  register: CLUSTER_CA_CERT

- name: register CLUSTER_ENDPOINT
  environment:
    KUBECONFIG: /.kube/config
  shell: kubectl {% raw %}config view --raw -o=go-template='{{range .clusters}}{{if eq .name "'''{% endraw %}{{CURRENT_CLUSTER.stdout}}{% raw %}'''"}}{{ .cluster.server }}{{end}}{{ end }}'{% endraw %}
  register: CLUSTER_ENDPOINT

- name: Use template to create kubeconfig.yaml
  vars:
    server: "https://{{hostvars[groups['k3s_cluster'][0]].ansible_host}}:6443"
  template:
    src: ./templates/kubeconfig.j2
    dest: /home/ubuntu/project/kubeconfig.yaml
