---
- name: create namespace
  ignore_errors: yes
  environment:
    KUBECONFIG: /.kube/config
  shell: |
    kubectl create namespace {{sample_app_name}}

- name: create serviceaccount
  ignore_errors: yes
  environment:
    KUBECONFIG: /.kube/config
  shell: |
    kubectl create serviceaccount -n {{sample_app_name}} github

- name: create rolebinding
  ignore_errors: yes
  environment:
    KUBECONFIG: /.kube/config
  shell: |
    kubectl create rolebinding -n {{sample_app_name}} github-editor --clusterrole=edit --serviceaccount={{sample_app_name}}:github

- name: create ghcr secret
  ignore_errors: yes
  environment:
    KUBECONFIG: /.kube/config
  shell: |
    kubectl create secret docker-registry ghcr --docker-server=ghcr.io --docker-username={{ghcr_username}} --docker-password={{ghcr_password}} --docker-email={{ghcr_email}} -n {{sample_app_name}}
