---
- name: Install python3-pip
  apt:
    name: python3-pip
    pkg:
      - python3-pip
- name: Install pip packages
  pip:
    name:
      - kubernetes==25.3.0
# - include: install-kubectl-cli.yml
# - include: create-github-deploy.yml
# - include: create-secrets.yml
# - include: create-k8s.yml
# - include: create-gitignore.yml
- include: create-kubeconfig.yml
