---
- name: Install python3-pip
  apt:
    name: python3-pip
    pkg:
      - python3-pip
- name: Install pip packages
  pip:
    name:
      - kubernetes==25.3.0
- include_tasks: install-kubectl-cli.yml
- include_tasks: create-github-deploy.yml
- include_tasks: create-secrets.yml
- include_tasks: create-k8s.yml
- include_tasks: create-gitignore.yml
- include_tasks: create-kubeconfig.yml
