---
- name: setup github agent
  when: "'gh-agents' in group_names"
  block:
    - name: Creates directory
      become: no
      file:
        path: /home/ubuntu/actions-runner
        state: directory

    - name: Download actions scripts
      become: no
      get_url:
        url: https://github.com/actions/runner/releases/download/v2.284.0/actions-runner-linux-arm64-2.284.0.tar.gz
        dest: /home/ubuntu/actions-runner

    - name: Extract actions script
      become: no
      ansible.builtin.unarchive:
        remote_src: yes
        src: /home/ubuntu/actions-runner/actions-runner-linux-arm64-2.284.0.tar.gz
        dest: /home/ubuntu/actions-runner

    - name: Install runner
      ignore_errors: yes
      become: no
      command: ./config.sh --url https://github.com/{{github_organisation}} --token {{github_runner_token}} --runnergroup Default --name {{github_runner_name}} --labelrs arm64 --work _work
      args:
        chdir: /home/ubuntu/actions-runner/

    - name: Install runner as service
      command: ./svc.sh install
      args:
        chdir: /home/ubuntu/actions-runner/

    - name: Start runner as service
      command: ./svc.sh start
      args:
        chdir: /home/ubuntu/actions-runner/
