---
- name: Clone zram project
  ansible.builtin.git:
    repo: 'https://github.com/StuartIanNaylor/zram-swap-config'
    dest: /home/ubuntu/zram-swap-config

- name: Changing perm of "/home/ubuntu/zram-swap-config/install.sh", adding "+x"
  file: dest=/home/ubuntu/zram-swap-config/install.sh mode=a+x

- name: Install zram
  command: sh ./install.sh
  args:
    chdir: /home/ubuntu/zram-swap-config

- name: Set COMP_ALG to lz4
  ansible.builtin.lineinfile:
    path: /etc/zram-swap-config.conf
    regexp: '^COMP_ALG='
    line: COMP_ALG=lz4

- name: Clone log2ram
  ansible.builtin.git:
    repo: 'https://github.com/azlux/log2ram'
    dest: /home/ubuntu/log2ram

- name: Changing perm of "/home/ubuntu/log2ram/install.sh", adding "+x"
  file: dest=/home/ubuntu/log2ram/install.sh mode=a+x

- name: Install log2ram
  command: sh ./install.sh
  args:
    chdir: /home/ubuntu/log2ram

- name: Set ZL2R to true
  ansible.builtin.lineinfile:
    path: /etc/log2ram.conf
    regexp: '^ZL2R='
    line: ZL2R=true

- name: Set COMP_ALG to true
  ansible.builtin.lineinfile:
    path: /etc/log2ram.conf
    regexp: '^COMP_ALG='
    line: COMP_ALG=lz4

- name: Set SIZE to true
  ansible.builtin.lineinfile:
    path: /etc/log2ram.conf
    regexp: '^SIZE='
    line: SIZE=100M

- name: Set LOG_DISK_SIZE to true
  ansible.builtin.lineinfile:
    path: /etc/log2ram.conf
    regexp: '^LOG_DISK_SIZE='
    line: LOG_DISK_SIZE=400M
