---
- include: update-host.yml
- include: install-ufw.yml
- include: install-log2ram.yml
- include: cmdline-edit.yml
- include: reboot-if-required.yml
- include: install-k3s.yml
- include: initialize-docker-registry.yml
- include: initialize-github-agent.yml
