---
- include_tasks: update-host.yml
- include_tasks: install-ufw.yml
- include_tasks: install-log2ram.yml
- include_tasks: cmdline-edit.yml
- include_tasks: install-k3s.yml
- include_tasks: initialize-docker-registry.yml
- include_tasks: initialize-github-agent.yml
