---
- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot
  when: cmdline.changed or reboot_required_file.stat.exists == true
  reboot:
    reboot_timeout: 3600
