---
- name: create namespace
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: falco

- name: create namespace
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: falco
        namespace: kube-system
      spec:
        targetNamespace: falco
        chart: falco
        repo: https://falcosecurity.github.io/charts
        valuesContent: |-
          jsonOutput: true
          jsonIncludeOutputProperty: true
          httpOutput:
              enabled: true
              url: "http://falcosidekick:2801/"
          discord:
              webhookurl: "https://discord.com/api/webhooks/904526554560868393/PnHHXaDKwkklhpEn8BEFX0zrTx0UVTllO2biMzJeflkGCicD35vumbo4H0e8Qs8zWqQd"
