---
- name: create namespace external-secrets
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: external-secrets

- name: create k8s secret (delete if exists)
  shell: kubectl delete secret awssm-secret --ignore-not-found

- name: create k8s secret
  shell: kubectl create secret generic awssm-secret --from-literal=access-key={{amazon_sm_access_key}} --from-literal=secret-access-key={{amazon_sm_secret_key}} --namespace=default

- name: install chart
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: external-secrets
        namespace: kube-system
      spec:
        targetNamespace: external-secrets
        chart: external-secrets
        repo: https://charts.external-secrets.io

- name: create secret store
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      metadata:
        name: secretstore-sample
        namespace: default
      spec:
        provider:
          aws:
            service: SecretsManager
            region: eu-central-1
            auth:
              secretRef:
                accessKeyIDSecretRef:
                  name: awssm-secret
                  key: access-key
                secretAccessKeySecretRef:
                  name: awssm-secret
                  key: secret-access-key
