---
- name: Ensures {{static_charts_directory}}/eck dir exists
  file:
    path: '{{static_charts_directory}}/eck'
    state: directory

- name: Download crds.yaml
  get_url:
    url: https://download.elastic.co/downloads/eck/1.8.0/crds.yaml
    dest: '{{static_charts_directory}}/eck/crds.yml'

- name: Download operator.yaml
  get_url:
    url: https://download.elastic.co/downloads/eck/1.8.0/operator.yaml
    dest: '{{static_charts_directory}}/eck/operator.yml'

- name: Apply manifests
  with_items:
    - '{{static_charts_directory}}/eck/crds.yml'
    - '{{static_charts_directory}}/eck/operator.yml'
  kubernetes.core.k8s:
    apply: yes
    src: '{{item}}'

- name: initialize elasticsearch
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: elasticsearch.k8s.elastic.co/v1
      kind: Elasticsearch
      metadata:
        name: quickstart
        namespace: default
      spec:
        version: 7.15.2
        nodeSets:
          - name: default
            count: 1
            podTemplate:
              spec:
                initContainers:
                  - name: sysctl
                    securityContext:
                      privileged: true
                    command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']

- name: initialize kibana
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: kibana.k8s.elastic.co/v1
      kind: Kibana
      metadata:
        name: quickstart
        namespace: default
      spec:
        version: 7.15.2
        count: 1
        elasticsearchRef:
          name: quickstart

- name: initialize filebeat
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: beat.k8s.elastic.co/v1beta1
      kind: Beat
      metadata:
        name: quickstart
        namespace: default
      spec:
        type: filebeat
        version: 7.15.2
        elasticsearchRef:
          name: quickstart
        config:
          filebeat.inputs:
            - type: container
              paths:
                - /var/log/containers/*.log
        daemonSet:
          podTemplate:
            spec:
              dnsPolicy: ClusterFirstWithHostNet
              hostNetwork: true
              securityContext:
                runAsUser: 0
              containers:
                - name: filebeat
                  volumeMounts:
                    - name: varlogcontainers
                      mountPath: /var/log/containers
                    - name: varlogpods
                      mountPath: /var/log/pods
                    - name: varlibdockercontainers
                      mountPath: /var/lib/docker/containers
              volumes:
                - name: varlogcontainers
                  hostPath:
                    path: /var/log/containers
                - name: varlogpods
                  hostPath:
                    path: /var/log/pods
                - name: varlibdockercontainers
                  hostPath:
                    path: /var/lib/docker/containers
