---
- name: download nginx chart
  get_url:
    url: https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.10.0/ingress-nginx-4.10.0.tgz
    dest: '{{static_charts_directory}}'

- name: apply chart
  kubernetes.core.k8s:
    apply: yes
    wait: yes
    definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: nginx-ingress
        namespace: kube-system
      spec:
        targetNamespace: kube-system
        chart: https://%{KUBERNETES_API}%/static/charts/ingress-nginx-4.10.0.tgz
        set:
          rbac.create: 'true'
          # this line below is required in cloudflare tunnel in configmap
          controller.service.type: ClusterIP
          controller.service.enableHttps: 'true'
          controller.metrics.enabled: 'true'
          controller.publishService.enabled: 'true'
