---
- name: download aws chart
  get_url:
    url: https://external-secrets.github.io/kubernetes-external-secrets/kubernetes-external-secrets-8.4.0.tgz
    dest: '{{static_charts_directory}}/aws.tgz'

- name: create namespace external-secrets
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: external-secrets

- name: create secret
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: aws-credentials
        namespace: external-secrets
      data:
        ACCESS_KEY: '{{amazon_sm_access_key}}'
        SECRET_KEY: '{{amazon_sm_secret_key}}'

- name: create helmchart
  kubernetes.core.k8s:
    apply: yes
    wait: yes
    definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: external-secrets
        namespace: kube-system
      spec:
        targetNamespace: external-secrets
        chart: https://%{KUBERNETES_API}%/static/charts/aws.tgz
        valuesContent: |-
          env:
            AWS_REGION: eu-central-1
          envVarsFromSecret:
            AWS_ACCESS_KEY_ID:
              secretKeyRef: aws-credentials
              key: ACCESS_KEY
            AWS_SECRET_ACCESS_KEY:
              secretKeyRef: aws-credentials
              key: SECRET_KEY
