---
- name: Install python3-pip
  apt:
    name: python3-pip
    pkg:
      - python3-pip
- name: Install pip packages
  pip:
    name:
      - kubernetes==29.0.0
- include_tasks: initialize-aws-secrets.yml
- include_tasks: initialize-external-dns.yml
- include_tasks: initialize-nginx.yml
- include_tasks: initialize-metrics-server.yml
- include_tasks: initialize-prometheus.yml
- include_tasks: initialize-hosted-runners.yml
- include_tasks: initialize-fan.yml
- include_tasks: add-local-coredns.yml
- include_tasks: initialize-cloudflared.yml
# not configured, not used even once:
# - include_tasks: falco.yml
# https://github.com/morriq/kubernetes-raspberry4b/issues/17
# - include_tasks: initialize-elk.yml