---
- name: Install python3-pip
  apt:
    name: python3-pip
    pkg:
      - python3-pip
- name: Install pip packages
  pip:
    name:
      - kubernetes
- include: initialize-aws-secrets.yml
- include: initialize-external-dns.yml
- include: initialize-nginx.yml
- include: initialize-metrics-server.yml
- include: initialize-prometheus.yml
- include: initialize-elk.yml
- include: initialize-auto-updates.yml
- include: initialize-fan.yml
