---
- name: Install python3-pip
  apt:
    name: python3-pip
    pkg:
      - python3-pip
- name: Install pip packages
  pip:
    name:
      - kubernetes==25.3.0
- include: initialize-aws-secrets.yml
- include: initialize-external-dns.yml
- include: initialize-nginx.yml
# https://github.com/morriq/kubernetes-raspberry4b/issues/17
# - include: initialize-elk.yml
- include: initialize-metrics-server.yml
- include: initialize-prometheus.yml
- include: initialize-fan.yml
- include: initialize-cloudflared.yml
# not configured, not used even once:
# - include: falco.yml
- include: add-local-coredns.yml
